sudo: required

services:
  - docker

jobs:
  include:
    - stage: deploy
    - script: ./scripts/docker/start_docker.sh
    - stage: test
    - script: bundle exec rake specs
    - stage: api-tester output
    - script: bundle exec rake api
