sudo: required

services:
  - docker

jobs:
  include:
    - stage: deploy
      script: ./scripts/docker/start_docker.sh && bundle exec rake specs
    - stage: api-tester output
      script: ./scripts/docker/start_docker.sh && bundle exec rake api
