swagger: "2.0"
info:
  description: "This is sample documentation for the demo API"
  version: "1.0.0"
  title: "Janky API"
host: "localhost:4567"
basePath: "/api/v1"
tags:
- name: "sheets"
  description: "Info Sheets"
schemes:
- "http"
paths:
  /sheets:
    get:
      tags:
        - "sheets"
      summary: "Retrieve all sheets"
      description: ""
      operationId: "getSheets"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Sheet"
    post:
      tags:
      - "sheets"
      summary: "Create a new info sheet"
      description: ""
      operationId: "addSheet"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Info sheet to add"
        required: true
        schema:
          $ref: "#/definitions/Sheet"
      responses:
        405:
          description: "Invalid input"
  /sheets/{sheetId}:
    get:
      tags:
      - "sheets"
      summary: "Find sheet by ID"
      description: "Returns a single sheet"
      operationId: "getSheetById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "sheetId"
        in: "path"
        description: "ID of sheet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Sheet"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Sheet not found"
    post:
      tags:
      - "sheets"
      summary: "Updates a sheet"
      description: ""
      operationId: "updateSheetWithForm"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "sheetId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Info sheet to add"
        required: true
        schema:
          $ref: "#/definitions/Sheet"
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "sheets"
      summary: "Deletes a sheet"
      description: ""
      operationId: "deleteSheet"
      produces:
      - "application/xml"
      parameters:
      - name: "sheetId"
        in: "path"
        description: "Sheet id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Sheet not found"
definitions:
  Skill:
    type: "object"
    properties:
      name:
        type: "string"
        example: "jazz"
      value:
        type: "integer"
        format: "int64"
    xml:
      name: "Skill"
  Sheet:
    type: "object"
    required:
    - "strenght"
    - "dexterity"
    properties:
      id:
        type: "string"
        format: "string"
      name:
        type: "string"
        example: "infoSheet"
      strength:
        type: "integer"
        format: "int64"
      dexterity:
        type: "integer"
        format: "int64"
      constitution:
        type: "integer"
        format: "int64"
      will:
        type: "integer"
        format: "int64"
      intelligence:
        type: "integer"
        format: "int64"
      charisma:
        type: "integer"
        format: "int64"
      skills:
        type: "array"
        items:
          $ref: "#/definitions/Skill"
    xml:
      name: "Pet"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
